spring:
  application:
    name: login
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/rewardsystem?useSSL=true&userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 8080
